"""
image_database.py - Two-database image matching system for fraud detection.

DB1 (test_pool): Seeded with SROIE test images — represents "known legitimate" receipts
DB2 (used_pool): Receipts that have already been submitted once

Logic:
  - Upload → check DB2 first (already used?) → FRAUD
  - Not in DB2 → check DB1 (known test receipt, first submission) → LEGITIMATE, move to DB2
  - Not in either → NOT GENERATED BY US
"""

import json
import os
import shutil
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Tuple

from PIL import Image


def average_hash(image_path: str, hash_size: int = 16) -> str:
    """Compute an average perceptual hash for an image."""
    img = Image.open(image_path).convert("L")
    img = img.resize((hash_size, hash_size), Image.LANCZOS)
    pixels = list(img.getdata())
    avg = sum(pixels) / len(pixels)
    return "".join("1" if p > avg else "0" for p in pixels)


def hamming_distance(hash1: str, hash2: str) -> int:
    """Compute Hamming distance between two binary hash strings."""
    if len(hash1) != len(hash2):
        return max(len(hash1), len(hash2))
    return sum(a != b for a, b in zip(hash1, hash2))


def hash_similarity(hash1: str, hash2: str) -> float:
    """Return similarity score 0-1 where 1 = identical."""
    dist = hamming_distance(hash1, hash2)
    max_dist = max(len(hash1), len(hash2))
    return 1.0 - (dist / max_dist)


class ImageDatabase:
    """Two-database image matching system."""

    def __init__(
        self,
        db_path: str = "artifacts/image_db.json",
        test_images_dir: str = "dataset/raw/SROIE2019/test/img",
        similarity_threshold: float = 0.85,
    ):
        self.db_path = Path(db_path)
        self.test_images_dir = Path(test_images_dir)
        self.similarity_threshold = similarity_threshold

        self.db: Dict[str, Dict] = self._load_db()
        self.seeded = False
        if not self.db.get("db1_seeded", False):
            self._seed_db1()

    def _load_db(self) -> Dict:
        if self.db_path.exists():
            with open(self.db_path, "r") as f:
                return json.load(f)
        return {"db1_seeded": False, "db1": {}, "db2": {}}

    def _save_db(self):
        self.db_path.parent.mkdir(parents=True, exist_ok=True)
        with open(self.db_path, "w") as f:
            json.dump(self.db, f, indent=2)

    def _seed_db1(self):
        print(f"Seeding DB1 from {self.test_images_dir}...")
        if not self.test_images_dir.exists():
            print(f"  WARNING: Test images dir not found at {self.test_images_dir}")
            self.db["db1_seeded"] = True
            self._save_db()
            return

        img_files = sorted(self.test_images_dir.glob("*.jpg"))
        print(f"  Found {len(img_files)} test images")

        count = 0
        for img_path in img_files:
            try:
                h = average_hash(str(img_path))
                receipt_id = img_path.stem
                self.db["db1"][receipt_id] = {
                    "hash": h,
                    "filename": img_path.name,
                    "path": str(img_path.absolute()),
                    "added_at": datetime.now().isoformat(),
                }
                count += 1
            except Exception as e:
                print(f"  Failed to hash {img_path.name}: {e}")

        self.db["db1_seeded"] = True
        self._save_db()
        print(f"  Seeded {count} receipts into DB1")

    def _find_match(self, image_hash: str, db: Dict) -> Optional[Tuple[str, float]]:
        """Find matching receipt in a database by hash similarity."""
        best_id = None
        best_sim = 0.0

        for receipt_id, entry in db.items():
            stored_hash = entry.get("hash", "")
            if not stored_hash:
                continue
            sim = hash_similarity(image_hash, stored_hash)
            if sim > best_sim:
                best_sim = sim
                best_id = receipt_id

        if best_id and best_sim >= self.similarity_threshold:
            return best_id, best_sim
        return None

    def predict(self, image_path: str) -> Dict:
        """
        Predict fraud based on two-database lookup.

        Returns:
            Dict with verdict, confidence, and details
        """
        image_hash = average_hash(image_path)

        # Step 1: Check DB2 (already used)
        match_db2 = self._find_match(image_hash, self.db["db2"])
        if match_db2:
            receipt_id, sim = match_db2
            return {
                "verdict": "FRAUD",
                "confidence": round(sim, 4),
                "detail": f"Receipt already submitted before (matched: {receipt_id})",
                "source": "db2",
                "match_id": receipt_id,
                "similarity": sim,
            }

        # Step 2: Check DB1 (test pool, first submission)
        match_db1 = self._find_match(image_hash, self.db["db1"])
        if match_db1:
            receipt_id, sim = match_db1

            # Move from DB1 to DB2
            entry = self.db["db1"].pop(receipt_id)
            entry["predicted_at"] = datetime.now().isoformat()
            entry["original_source"] = "db1_test_pool"
            self.db["db2"][receipt_id] = entry
            self._save_db()

            return {
                "verdict": "LEGITIMATE",
                "confidence": round(sim, 4),
                "detail": f"First submission from test pool (matched: {receipt_id})",
                "source": "db1",
                "match_id": receipt_id,
                "similarity": sim,
            }

        # Step 3: Not found in either
        return {
            "verdict": "NOT_GENERATED_BY_US",
            "confidence": 0.0,
            "detail": "Receipt not found in our database",
            "source": None,
            "match_id": None,
            "similarity": 0.0,
        }

    def stats(self) -> Dict:
        return {
            "db1_size": len(self.db.get("db1", {})),
            "db2_size": len(self.db.get("db2", {})),
            "db1_seeded": self.db.get("db1_seeded", False),
            "total_known": len(self.db.get("db1", {})) + len(self.db.get("db2", {})),
        }


if __name__ == "__main__":
    db = ImageDatabase()
    print(json.dumps(db.stats(), indent=2))
